### ISSUE TITLE
could you provide bag files for 6D localization?

### ISSUE THREAD

**Issue by weisongwen** [AravindaDP/humanoid_navigation#2]
Firstly, thanks for your excellent work.

These days I am working on the **humanoid_localization** package, could you pls provide bags file containing the topics and tf needed by the **humanoid_localization** package? such as the IMU, Tf (containing the information of odometry), pointCloud....

Thanks !

**Comment by AravindaDP** [comment]
@weisongwen 

To be clear I only maintain a copy of the humanoid_navigation ros stack developed by Armin Hornung (for the purpose of releasing as a prebuilt binary package through ros build farm) https://github.com/ahornung/humanoid_navigation

So could you kindly forward your request to the original author?

Apologies for not being able to cater for your specific request.

**Comment by weisongwen** [comment]
Thanks a lot anyway ! I will ask ahornung directly. 

do you know whether the humanoid_localization package could be used in Velodyne Lidar PointCloud2 in mapping?
